#include <pcap.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include "radiotap.h"
#include "beacon_frame.h"
#include "wireless.h"